name: Tests

on:
  pull_request_target:

  push:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    strategy:
      matrix:
        go-version:
          - '1.13'
          - '1.14'
          - '1.15'
          - '1.16'
          - '1.17'

        operating-system:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'

    runs-on: ${{ matrix.operating-system }}
    name: 'Go ${{ matrix.go-version }}: Test on ${{ matrix.operating-system }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Todo
        run: |
          echo "foo"
          echo "$GOPATH/pkg/mod/"
          echo "foo"

          ls -Al "$GOPATH/pkg/mod/"

      - name: Run tests
        timeout-minutes: 3
        run: go test ./...

  code-coverage:
    needs:
      - test

    runs-on: 'ubuntu-latest'
    name: 'Code coverage'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Calculate coverage
        timeout-minutes: 5
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Todo
        run: |
          ls -Al
          ls -Al "$GOPATH/pkg/mod/"
